FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt-get update && \
    apt-get install -y file && \
    apt-get install -y xz-utils && \
    apt-get install -y zip && \
    apt-get install -y snapd