name: Flutter Build

on:
  push:
    branches:
    - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: smoke test
        working-directory: ./app
        run: flutter test

      - name: build flutter web
        working-directory: ./app
        run: flutter build web

      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: flutterbuildartifact
          # File path
          path: ./app
          # Behaviour if no files found at path
          if-no-files-found: error
          # Days until artifact expires
          retention-days: 90
          # Overwrites if artifact with same name exists
          overwrite: true
