name: Flutter

on:
  push:
    branches:
    - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: smoke test
        working-directory: ./app
        run: flutter test

      - name: build flutter web
        working-directory: ./app
        run: flutter build web

      - name: Deploy
        uses: ./.github/workflows/deploy.yml
