name: Flutter Web App Deploy

on:
  workflow_run:
    workflows: ["Flutter Build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: List Available Artifacts
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_PAGES }}
          script: |
            const artifacts = await github.actions.listArtifacts({ owner: context.repo.owner, repo: context.repo.repo });
            console.log(artifacts);


      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          # Download artifact name
          name: flutterbuildartifact
          # Directory to store download
          path: ./app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES }}
          publish_dir: ./app/build/web
